### ISSUE TITLE
Delete this?

### ISSUE THREAD

**Issue by katyhuff** [ucb-rdn/ucb-rdn.github.com#15]
Hi Folks, I think given that neutronics.nuc.berkeley.edu exists (even though it's still in development), this site should be deprecated. 

I also think that since folks aren't using this organization, we should delete it. I created it, so I can do that. I just feel like I shouldn't do that without the go ahead from @rachelslaybaugh  at least. 

It's possible there are things that should be moved to the new site. Let me know what you think @rachelslaybaugh . The only things that need to be ported, probably, are the projects ([MocDown](http://ucb-rdn.github.io/projects/mocdown/mocdown.html) and [WARP](http://ucb-rdn.github.io/projects/warp/warp.html)). Possibly the descriptions of the alumni (like Ryan and Jeff) deserve to be ported over as well.

**Comment by rachelslaybaugh** [comment]
Hi,

Yes, we should get rid of this I think. Ryan and Jeff would be good. We
have some current project descriptions ready for the new site, but having
these to draw from would also be good. Do you want to just put them in the
people and projects google docs? I can re-share (or share?) if needed.


Rachel

**Comment by katyhuff** [comment]
Will do. Thanks Rachel!

**Comment by katyhuff** [comment]
hmmm.. sorry.. so.. ryan and jeff didn't have bios that match the template. We can just use their pictures and state where they are now. 

Also, yes, I can't find the project doc. If you could reshare that with me, I'll do the rest.
